### ISSUE TITLE
GPU to CPU compatibility

### ISSUE THREAD

**Issue by jduerholt** [atomistic-machine-learning/schnetpack#195]
Dear SchnetPack developers,

if I train my model using the GPU (device: "cuda"), I cannot use it on the CPU (device: "cpu"). Is this a constraint of using pytorch under the hood or can it be fixed?

Best,

Johannes

**Comment by Stefaanhess** [comment]
Hey @jduerholt ,

did you use ``map_location="cpu"`` when loading the model?
Normaly it should be possible to load GPU models to the CPU by using:

``
model = torch.load("model_path", map_location="cpu")
``

Best,
Stefaan

**Comment by jduerholt** [comment]
Thank you very much. I did not know this command. I set only the device keyword of the ml_calculator class to "cpu" and it failed. Thanks for your help. Now it works!

**Comment by Stefaanhess** [comment]
Great!
@mgastegger : I updated the calculator, to move the ml_model to the desired device before running the calculations.

**Comment by pschienbein** [comment]
Dear SchNetPack developers,

Closely related to this issue, there is another problem if the training has been performed using multiple GPUs and the model is to be used on a CPU. I employ multiple GPUs by using the torch.nn.DataParallel object. This splits the given model into chunks to be parallelizable, while the original model is retained (and also updated!) (https://pytorch.org/docs/stable/nn.html#dataparallel). 
During training, SchNetPack saves the DataParallel object. However, this object cannot be utilized by a CPU device directly, even if the `map_location='cpu'` parameter is specified. The way I circumvented the problem is that I added 

```
if isinstance(model, torch.nn.DataParallel) and map_location == torch.device('cpu'):
        model = model.module
```

after `model = torch.load(model_path, map_location=map_location)` in spk_utils.py. 
This extracts the original serial module from the DataParallel object but only if the cpu device is requested. This definitely is an ugly workaround, however, works in my case and does not change the behavior when running in a CUDA environment. Another possibility would be that the trainer always saves the original module instead of the DataParallel model.

Best, 
Philipp
