### ISSUE TITLE
'AtomisticModel' object has no attribute 'requires_stress'

### ISSUE THREAD

**Issue by saeid0021** [atomistic-machine-learning/schnetpack#198]
Hi everyone!

I've just met SchNetpack and I'm trying to use "[Trained Models](https://schnetpack.readthedocs.io/en/stable/getstarted/benchmarks.html#trained-models)" for predicting energy_U0 but in the last step, this error appears:
` 'AtomisticModel' object has no attribute 'requires_stress'`

```
import os
import schnetpack as spk
import ase
import torch

device = "cuda"

from schnetpack.datasets import QM9
qm9data = QM9('./qm9.db', download=True, load_only=[QM9.U0], remove_uncharacterized=True)

atoms = ase.io.read('file.xyz', format='xyz')
best_model = torch.load(os.path.join(qm9tut, 'best_model'))

calculator = spk.interfaces.SpkCalculator(model=best_model, device=device, energy=QM9.U0)
atoms.set_calculator(calculator)
print('Prediction:', atoms.get_total_energy())
```

I also tried to do the evaluation on test data on documentation, the same error appeared.

**Comment by mgastegger** [comment]
We introduced the possibility to calculate stress tensors recently, which is why older models yield the above error. To avoid this issue, we added the `load_model` function to `utils`, which can be used to savely load models before the addition of the stress tensor.

If you replace
`best_model = torch.load(os.path.join(qm9tut, 'best_model'))`
with
`best_model = spk.utils.load_model(os.path.join(qm9tut, 'best_model'))`
it should work again.
