### ISSUE TITLE
AtomsData properties dtypes

### ISSUE THREAD

**Issue by giadefa** [atomistic-machine-learning/schnetpack#201]
Hi,
you seem to be storing the dtype in the database, but then the properties are always converted to a FloatTensor:

https://github.com/atomistic-machine-learning/schnetpack/blob/d45ae7523f3232bfc349ec25e9f9b3f26d14358a/src/schnetpack/data/atoms.py#L361

I would have expected:
`properties[pname] = torch.from_numpy(prop)`

**Comment by mgastegger** [comment]
Hi,

currently the dtype is only present because of how we store data. All properties are stored in binary format in order to save storage space. To convert back to floats, one needs to know the dtype.

We usually assume, that training/prediction is carried out on a GPU due to the speedup, hence we use FloatTensors as default, as GPUs typically only support single precision.

Did you encounter any problems with this convention?

**Comment by giadefa** [comment]
I was saving a dtype=np.int64 array to keep track of some conformations
(not used for training) but the result is of course wrong with a forced
conversion to float without providing any error message.
Given that AtomData provides a dataset, maybe allowing for different Tensor
types would be useful.

**Comment by mgastegger** [comment]
We will have a look. It also seems that ASE now automatically stores data in binary format, which would make our current approach superfluous.

**Comment by giadefa** [comment]
It would also be nice to extend datasets from datasets rather than exposing
the storage mechanism in __init__, e.g.

for instance:

from collections import OrderedDict

class CachedDataset(Dataset):#TODO: UNTESTED
def __init__(self, dataset, cache_size=200000):
self.dataset = dataset
self.cache_size = cache_size
self.cache = OrderedDict()

def __getitem__(self, idx):
if self.cache.get(str(idx)) is not None:
return self.cache.get(str(idx))
else:
if len(self.cache.keys())>=self.cache_size:
self.cache.popitem(last=False) #remove first
self.cache[str(idx)]=self.dataset[idx]
return self.cache[str(idx)]

def __len__(self):
return len(self.dataset)

**Comment by giadefa** [comment]
it would be nice to have a dataset class which uses the ASE DB and numpys array as input/output types and another class which extends it,  providing what is required by schenetpack (e.g. torch.Tensor)

**Comment by Stefaanhess** [comment]
Hi @giadefa ,
we have been thinking about this when we implemented changes on the dataset class, but we decided to not split the dataset into a "dataprovider" which provides np-arrays and a "dataset-wrapper" for training, since there are no other useful types of dataproviders yet. The ase.db tools do also provide the necessary functions in order to get the np-arrays :)
