### ISSUE TITLE
Loading molecules from ASE in MD System object

### ISSUE THREAD

**Issue by jstoppelman** [atomistic-machine-learning/schnetpack#212]
Hello, first, thank you for making this useful software available! I think I'm experiencing a bug in the System class when trying to run a MD simulation with Schnetpack. See the following code:

```
md_system = System(1, device="cuda")
md_system.load_molecules(traj)
```
This gives a TypeError:
`TypeError: 'SimpleNeighborList' object is not callable`

This traces back to lines 180-181 in the "system.py" file located in the "md" subdirectory:
```        
if self.neighbor_list is not None:
    self.neighbor_list = self.neighbor_list(self)
``` 

I'm able to fix this by removing the function call in the second line:
```
if self.neighbor_list is not None:
    self.neighbor_list = self.neighbor_list
```
but I'm not sure if this is the best way to fix this. I'm actually not share why this error would come up, because I think 
```
self.neighbor_list(self)
```
does seem necessary for this part of the code to work...
EDIT: I believe this error will only occur if you make a System object and then call "load_molecules" twice. 

Additionally, passing in one molecule into System.load_molecules leads to some problems for some reason. Namely, on line 127
```
self.n_molecules = len(molecules)
```
returns the number of atoms in the ase.Atoms object instead of the number of molecules, as I guess that's what happens without a list of Atoms objects. This leads to other problems, like on line 134-135:

```
for i in range(self.n_molecules):
     self.n_atoms[i] = molecules[i].get_number_of_atoms()
```
the for loop is over the number of atoms in the object, making molecules[i] a Atom object instead of Atoms object, which doesn't have the get_number_of_atoms() function.

I can write a fix for this for my own use, but I wanted to draw this to your attention in case you believe having a fix for this in the main code is worthwhile.

**Comment by mgastegger** [comment]
Hi, thank you for the feedback. The neighbor list issue does indeed happen when calling the `load_molecules` routine twice. Once the molecules are loaded the neighbor list is already initialized leading to the error. We are currently working on a release where we have moved the neighbor list to the calculator, which will solve this issue.
Regarding the `load_molecules` function, it expects a list of `ase.Atoms` (or trajectory) as input. It is done this way, because several molecules can be simulated in parallel when using the GPU. If you want to simulate a single molecule, it should be packed into a list e.g. `[mol]`. We could add a check to do this automatically, if this would help.

**Comment by jstoppelman** [comment]
Thank you, I just thought of making a list to contain the singular `ase.Atoms` object myself and that should fix things. I do think a check for this could be useful though. Thank you for the comments, I have no other problems on my end. Should I close this issue?

**Comment by mgastegger** [comment]
This will be fixed in the next release.
