### ISSUE TITLE
incorporate other descriptors

### ISSUE THREAD

**Issue by neojie** [atomistic-machine-learning/schnetpack#215]
Hi,
I was trying to incorporate other descriptors using a recent package `Dscribe`. `Dscribe` use `ase` atoms object as input and output the representation.  In other words, I want to combine the well established training framework of  `schnetpack`'s and the versatile representation generation tool `Dscribe`. 
I was able to train the energy. But for the force, because it is a derivative of energy and because I use `Dscribe` as a black box to compute the representation, the `position` properties of atoms does not explicitly appears in the neural network I built. As a result, when I tried to train the model that includes the force, I got the error `RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.`
Do you know a way of including `position` in the network while using external tools like `Dscribe` to compute the representation?
Thank you!

**Comment by mgastegger** [comment]
I am happy to hear that you like the SchNetPack training framework!

Unfortunately, I'm afraid, there is no quick way to incorporate the forces in the above setup. The problem is, as you described, the derivative with respect to the positions. If descriptors are used, the force is computed via the chain rule
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbf{F}_\alpha&space;=&space;-\sum_i^{N_\mathrm{Atoms}}&space;\sum_d^{N_\mathrm{Desc.}}&space;\frac{\partial&space;E_i}{\partial&space;D_d}&space;\frac{\partial&space;D_d}{\partial&space;\mathbf{R}_\alpha}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbf{F}_\alpha&space;=&space;-\sum_i^{N_\mathrm{Atoms}}&space;\sum_d^{N_\mathrm{Desc.}}&space;\frac{\partial&space;E_i}{\partial&space;D_d}&space;\frac{\partial&space;D_d}{\partial&space;\mathbf{R}_\alpha}" title="\mathbf{F}_\alpha = -\sum_i^{N_\mathrm{Atoms}} \sum_d^{N_\mathrm{Desc.}} \frac{\partial E_i}{\partial D_d} \frac{\partial D_d}{\partial \mathbf{R}_\alpha}" /></a>, 
where <a href="https://www.codecogs.com/eqnedit.php?latex=\frac{\partial&space;E_i}{\partial&space;D_d}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{\partial&space;E_i}{\partial&space;D_d}" title="\frac{\partial E_i}{\partial D_d}" /></a> is the derivative of the energy network (here in an atomistic setup) wrt. its inputs (the descriptor) and <a href="https://www.codecogs.com/eqnedit.php?latex=\frac{\partial&space;D_d}{\partial&space;\mathbf{R}_\alpha}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{\partial&space;D_d}{\partial&space;\mathbf{R}_\alpha}" title="\frac{\partial D_d}{\partial \mathbf{R}_\alpha}" /></a> is the derivative of the descriptor wrt. to the positions. Both terms are needed. If SchNetPack is coupled with external descriptors, you would only be able to obtain the first term, since the positions are not part of the computational graph.

There are in principle 2 ways to solve this:
-) Implement the descriptors as a torch module, where grad is enabled for the positions. In this manner, one could propagate through the whole model. This has the huge disadvantage that the descriptors in `Dscribe` would have to be implemented as torch code.

-) Make use of the chain rule. The first term can be obtained with autograd in SchNetPack, the second term you would have to compute in the descriptor package. Having these two quantities, one could modify a SchNet model class to compute the total force using the chain rule above. This is the more realistic approach, although it is still a significant effort. In theory, it should be possible to get these terms via the numpy autograd package.

**Comment by neojie** [comment]
I see. Do you have any plans to incorporate more descriptors in Schnetpack in the near future?

**Comment by Stefaanhess** [comment]
@neojie, we are planning to implement different representation modules for future versions.
