### ISSUE TITLE
Atomrefs, where do they come from?

### ISSUE THREAD

**Issue by bkmi** [atomistic-machine-learning/schnetpack#218]
Where do the atomref numbers come from?

The only documentation I have found about them hasn't been specific.
[Here](https://schnetpack.readthedocs.io/en/stable/tutorials/tutorial_02_qm9.html#Dataset-statistics) is where they are discussed in the tutorial.
[Here](https://schnetpack.readthedocs.io/en/stable/modules/atomistic.html#schnetpack.atomistic.Atomwise) is the documentation for the function in which they are used.

**Comment by mgastegger** [comment]
In general, these are the energies computed for the free atoms (single atom in vacuum).

There are two ways how they can enter SchNetPack.

First, if using `spk_run.py`, SchNetPack only makes use of them if they are given in the metadata of the dataset (e.g. in QM9). To be specific, two entries are needed in the metadata:
- `atref_labels`: list of the properties for which atomrefs are available
- `atomrefs`: a list with the associated values. This is typically created from a numpy array, which has the shape `max_atom_type+1` x `len(atref_labels)`. I will generally refer to it as an array.

An example would be: I have the properties `U0` and `H`. The `atref_labels` entry would be
`['U0', 'H']`. Let's say, my highest element is Fluorine with an atomic charge of 9. Then the `atomrefs` array would have the shape (9+1)x2, since I have two properties. Each column of `atomrefs` corresponds to a property in `atref_labels` (using the same order). The row corresponding to an atomic number would then contain the atomref value for that atom type and property. E.g. for the present example, in `atomrefs[1,0]` I would have `U0` of the Hydrogen, `atomrefs[6,0]` would be Carbon etc.

The full metadata would be generated along the lines of this:
```
metadata = {
        'atref_labels' : ['U0', 'H'],
        'atomrefs' : atomref_array.tolist()
    }
```

The second way is by passing them to an `Atomwise` based layer via the `atomref` keyword. Here, the column of the above `atomrefs` corresponding to the property to be modeled should be used (which is an `max_atom_type+1` x 1 array).

**Comment by bkmi** [comment]
Thank you for your answer but I should have been more specific. From where do you calculate the atomrefs? Do you create a schnet model without them then average across contributions from certain atoms? I want to know where the values built in to QM9 came from.

**Comment by bkmi** [comment]
I think I found my answer:
https://www.nature.com/articles/sdata201422#Sec4

It's in the qm9 paper.

**Comment by mgastegger** [comment]
Thats correct.
