### ISSUE TITLE
Reproducing results 

### ISSUE THREAD

**Issue by linhlpv** [atomistic-machine-learning/schnetpack#222]
Hi, I am reproducing the results of SchNet as one of works for my thesis. I found [Trained model](https://schnetpack.readthedocs.io/en/stable/getstarted/benchmarks.html#trained-models) in the documents of SchNet. But when I run it , I found somethings wrong with the split.npz file. When setting of the training in ***args.json*** file, **remove_uncharacterized** is set to be true, the size of the qm9.db must be 130831 mols. But the total idx in split file is 133885 (the fullsize). And when I run the model eval on this idx of the test db, the loss is much less than the one reported in the papers. So I think some mistakes in the ***split.npz*** file.
Could you help me, plz?
Please answer me soon! Thank you so much!

**Comment by Stefaanhess** [comment]
Hi @L3viAckerman ,
I will check the split file tomorrow.
Best regards,
Stefaan

**Comment by L3viAckerman** [comment]
Hi @Stefaanhess , thank you so much!

**Comment by Stefaanhess** [comment]
Ok, I found the issue.
The --remove_uncharacterized argument is only used to select which datapoints are written to the db file. If the database does already exist, the argument is ignored. I think the benchmark models have been created with the use of an existing (full size) dataset and the uncharacterized molecules have not been removed for training. I will fix this and maybe also update the trained models.
For now you could delete your existing qm9.db file before running the training script. This should work until the fix is ready.

**Comment by L3viAckerman** [comment]
Hi @Stefaanhess 
Thank you so much! Could you update the trained model and public it? I really need the model to benchmark but I only have the Colab to use, so I can retrain all of them.
Thank you again for your helping!

**Comment by hsukiang** [comment]
Hello there,
I have clone the Gschnet and tried to train the model from scratch. However there is an error with the split file (split.npz)? Is that similar to this issue ? Thank you for your time. 

`(gschnet) jameshko@jameshko-HP:~/Documents/researchnrc/QED/gschnet$ python ./G-SchNet/gschnet_qm9_script.py train gschnet ./data/ ./models/gschnet/ --cuda
INFO:root:Random state initialized with seed 509646212 
INFO:root:QM9 will be loaded...
INFO:schnetpack.data.atoms:Starting download
INFO:root:Downloading GDB-9 atom references...
INFO:root:Done.
INFO:root:Downloading GDB-9 data...
INFO:root:Done.
INFO:root:Extracting data from tar file...
INFO:root:Done.
INFO:root:Parsing xyz files...
INFO:root:Parsed:  10000 / 133885
INFO:root:Parsed:  20000 / 133885
INFO:root:Parsed:  30000 / 133885
INFO:root:Parsed:  40000 / 133885
INFO:root:Parsed:  50000 / 133885
INFO:root:Parsed:  60000 / 133885
INFO:root:Parsed:  70000 / 133885
INFO:root:Parsed:  80000 / 133885
INFO:root:Parsed:  90000 / 133885
INFO:root:Parsed: 100000 / 133885
INFO:root:Parsed: 110000 / 133885
INFO:root:Parsed: 120000 / 133885
INFO:root:Parsed: 130000 / 133885
INFO:root:Done.
INFO:root:Downloading pre-computed list of invalid QM9 molecules...
INFO:root:Done.
INFO:root:
Pre-processing data...
INFO:root:Processed:      0 / 133885...
INFO:root:Processed:  10000 / 133885...
INFO:root:Processed:  20000 / 133885...
INFO:root:Processed:  30000 / 133885...
INFO:root:Processed:  40000 / 133885...
INFO:root:Processed:  50000 / 133885...
INFO:root:Processed:  60000 / 133885...
INFO:root:Processed:  70000 / 133885...
INFO:root:Processed:  80000 / 133885...
INFO:root:Processed:  90000 / 133885...
INFO:root:Processed: 100000 / 133885...
INFO:root:Processed: 110000 / 133885...
INFO:root:Processed: 120000 / 133885...
INFO:root:Processed: 130000 / 133885...
INFO:root:Processed: 133885 / 133885...
INFO:root:... successfully validated 132970 data points!
INFO:root:915 structures were removed because they are on the pre-computed list of invalid molecules!
INFO:root:
Compressing and storing statistics with numpy...
INFO:root:Done! Pre-processing needed 0h01m12s.
INFO:root:create splits...
Traceback (most recent call last):
  File "./G-SchNet/gschnet_qm9_script.py", line 716, in <module>
    main(args)
  File "./G-SchNet/gschnet_qm9_script.py", line 635, in main
    split_file=split_path)
  File "/home/jameshko/anaconda3/envs/gschnet/lib/python3.7/site-packages/schnetpack/data/atoms.py", line 135, in create_splits
    return train_test_split(self, num_train, num_val, split_file)
  File "/home/jameshko/anaconda3/envs/gschnet/lib/python3.7/site-packages/schnetpack/data/partitioning.py", line 40, in train_test_split
    "You have to supply either split sizes (num_train /"
ValueError: You have to supply either split sizes (num_train / num_val) or an npz file with splits.
`

**Comment by L3viAckerman** [comment]
Hi @hsukiang , could you check the size of the db, and the total idx in the split? Maybe the error is the size of the db is not match with the split file. 
And one question, where is the split file you use from?

**Comment by NiklasGebauer** [comment]
Hello @hsukiang, your problem should not be related, I think you can fix it by providing the --split parameter, it is missing in the line provided in the G-SchNet readme. Thanks for reporting the problem, i will fix the call in the documentation. The correct line to reproduce the paper results is:

`python ./G-SchNet/gschnet_qm9_script.py train gschnet ./data/ ./models/gschnet/ --cuda --split 50000 5000`

This will use 50k molecules as training set, 5k for validation, and the remaining ~78k are reserved as a test set.
Let me know if you're running into any other problems when reproducing the results!
