### ISSUE TITLE
MD Simulation with SchNetCalculator

### ISSUE THREAD

**Issue by jwz360** [atomistic-machine-learning/schnetpack#227]
Hi! My MD system has over 600 atoms. I have finished training a model. However, when I use model to try MD simulation, there are two situations: 1. employing "CPU" as device, it shows that buffers on device "cuda" but model on device "cpu“; 2. employing "cuda" as device, it shows CUDA out of memory. I want to know why buffers on device "cuda" or how to set parallel when performing MD simulations.
 Thank you so much!

**Comment by mgastegger** [comment]
Hi, unfortunately the MD code has no parallel version yet. Parallelization in pytorch works by distributing mini-batches to different GPUs, which is easy to do during training. However, in standard MD one usually has a single molecule. In order to compute this on more than one GPU, the systems would need to be split in different fragments, which then need to be evaluated independently. 
This could be done for e.g. Behler type symmetry functions but in descriptors like SchNet the atoms interact with each other across multiple layers and the system cannot be split in straightforward manner anymore.

**Comment by mgastegger** [comment]
Out of interest, which neighborlist/cutoff do you use and how large is the VRAM of your GPU?
For 6 Angstrom cutoff, periodic boundary conditions and ASE neighbor list systems with ~1000 atoms can be simulated on a 16GB GPU.

**Comment by jwz360** [comment]
Thanks for your reply! For 6 Angstrom cutoff, I failed to perform MD simulation with  640 atoms by 12GB GPU.

**Comment by mgastegger** [comment]
Ah, one thing I forgot, the current MD code in the master branch uses a brute force pairwise neighbor list, which is far from optimal for large systems especially wrt to memory usage. You might want to try out the pbc_update branch, where you can specify one of the other neighbor list. For this, you would have to adapt the `calculator` block in the input along these lines (`cutoff` uses the distance units used for training the model):
```
calculator:
  type: schnet
  model_file: path/to/model
  required_properties:
  - energy
  - forces
  cutoff: 5.0
  #neighbor_list: simple
  #neighbor_list: torch
  neighbor_list: ase
```

**Comment by jwz360** [comment]
@mgastegger  Thanks for your advice!
