### ISSUE TITLE
Restart Training

### ISSUE THREAD

**Issue by jwz-ecust** [atomistic-machine-learning/schnetpack#231]
Hi! I want to know how to restart training once the training job was interrupted. Also, is there any method to train a new model based on the pre-trained model.

**Comment by mgastegger** [comment]
Training is restarted automatically if you re-execute your training command (`spk_run.py ...`) specifying the same training folder (just make sure not to use the `--overwrite` flag). Instead of using the full training command, it is also possible to call schnetpack via `spk_run.py from_json <MODELDIR>/args.json`, which will read in the settings from the previous run and restart training.

Using only command line options, there is no simple way to start training from a pretrained model yet. A hacky way to still achieve this would be using the above restart mechanism. One could restart training from a copy of the initial model directory, adapting `args.json` to the new data path (`datapath`), model directory (`modelpath`) and training settings (lr, decay, etc). The model architecture should of course be kept the same.

**Comment by Stefaanhess** [comment]
@jwz-ecust does this solve the issue?
