### ISSUE TITLE
Trainer does not restore "stopped" state

### ISSUE THREAD

**Issue by sirmarcel** [atomistic-machine-learning/schnetpack#239]
Hello,

I have a quick question about the `Trainer` class: 

The `Trainer` does not remember whether it has already stopped or not. If you train with a LR plateau hook, the following happens: After training to convergence, the `Trainer` terminates as expected. Then, if you restore it from the latest checkpoint, it runs *again* for a few more epochs, presumably until the hook triggers again. You can repeat this indefinitely. Is this expected behaviour? 

If this is not expected, I'd be happy to submit a small PR to fix it -- you simply need to add `self._stop` to the `state_dict`.

Thanks!

**Comment by Stefaanhess** [comment]
Hey @sirmarcel ,

I am not sure why someone would train a model until convergence and then run `trainer.train()` again, without changing the lr-settings :D
Saving `self._stop` to the state dict would prohibit any retraining of the model at all. In case someone uses the `MaxEpochHook`, trains the model for x epochs and then tries to train for some more epochs, it would be the easiest to overwrite the `MaxEpochHook` with a different number of epochs. `trainer.train()` would still not do anything, because `self._stop = True`. Maybe I could add a `on_train_begin`-function to the `ReduceOnPlateau`-hook, which checks if the lr is already below the min_lr. This would then stop the training directly if the `min_lr` has not been updated.
Does this sound good to you?

**Comment by sirmarcel** [comment]
Hi Stefan,

> I am not sure why someone would train a model until convergence and then run trainer.train() again, without changing the lr-settings :D

That's a good question 😆 ! In my case, I was just testing some automation on top of `Trainer` and was confused that it kept running after converging initially. I would expect the `Trainer` to either be finished or not, independently of whether it was restored from a checkpoint, so running `.train()` should run at most one step before finishing again. 

Thanks for explaining the idea behind not saving `_stop`! In my case, the actual culprit is the `EarlyStoppingHook`, which I was also using, but forgot to mention. (I'm using the plateau hook without its `min_lr` option, so it's not responsible for terminating the training.)

The `EarlyStoppingHook` doesn't save the `best_loss` to its own `state_dict`, so when it gets restored, it automatically resets its counter to 0 (since it initialises with `best_loss = float("inf)`). Therefore, a recovered `Trainer` with early stopping will always run for at least the `patience` of the hook. Would you consider this a bug? I guess in some cases it might be preferable to get "another chance" at training further, but maybe the correct way to achieve that is to modify the hooks?

**Comment by Stefaanhess** [comment]
Hey Marcel,

> The EarlyStoppingHook doesn't save the best_loss to its own state_dict, so when it gets restored, it automatically resets its counter to 0 (since it initialises with best_loss = float("inf)). Therefore, a recovered Trainer with early stopping will always run for at least the patience of the hook.

Oh ok, I think it would be good to also store the `best_loss`. I am not sure what the best behaviour for converged models is. Since e.g. the `MaxEpochHook` directly aborts training, when the maximum number of epochs is reached, it would make sence to also use this behaviour for other stop-hooks.
@ktschuett : Should converged models be able to train until they converge again (without an update of the Hook-parameters), or should the training be aborted at the beginning of training?

**Comment by ktschuett** [comment]
> @ktschuett : Should converged models be able to train until they converge again (without an update of the Hook-parameters), or should the training be aborted at the beginning of training?

I think the trainng should abort directly if you don't change the patience or any other training parameter. It should behave as if it never was interupted.

**Comment by Stefaanhess** [comment]
Ok, I will have a look at the hooks and fix them if necessary.

**Comment by sirmarcel** [comment]
Thanks, Kristof and Stefan! Really appreciate it.

@Stefaanhess: If you're having a look anyways, I think there's a bug in the `Trainer` state restoration: [This line](https://github.com/atomistic-machine-learning/schnetpack/blob/cd8bc502323a0f3c785dba8a3efe4eaae0002686/src/schnetpack/train/trainer.py#L114) should be using `state_dict` instead of `self.state_dict`, otherwise the hook state gets lost on recovery. :) 

This fix, and adding `best_loss` to the `EarlyStoppingHook` `state_dict` mostly fix the restart problem for me: now the `Trainer` runs for just one epoch.

**Comment by sirmarcel** [comment]
Took the liberty of opening a PR (#243) to fix this issue, I think as discussed!

**Comment by Stefaanhess** [comment]
Hey @sirmarcel ,
thanks for your contribution. The PR has been merged now :)
