### ISSUE TITLE
Applying torch.autograd.grad with less memory

### ISSUE THREAD

**Issue by OMalenfantThuot** [atomistic-machine-learning/schnetpack#304]
Hi all!
This is not really an issue, more of a question.
We've been applying some Schnet networks to very large supercells (5000+ atoms), but we were hoping to go even higher.
At a certain point, the CUDA memory runs out when calculating forces or higher order derivatives using torch.autograd.grad.
The memory requirements scale linearly with the number of atoms as a computational graph must be remembered for each atom, so we hit a wall pretty fast.
I was wondering if you ever looked into that limitation and if some tool already exist that would calculate derivatives individually for each atom instead of for the system as a whole, even tough it would come at the expanse of speed.
I'll be working on this in any case and see what I can achieve.

Thanks a lot!
Olivier

**Comment by ktschuett** [comment]
Sorry for the late response. We are waiting for the forward mode autograds in PyTorch, which are expected with the next release ([see PyTorch thread](https://github.com/pytorch/pytorch/issues/10223)). Then, this should be possible.

**Comment by OMalenfantThuot** [comment]
After some testing, my impression is that it would only be possible while using a single interaction block, otherwise the representation of each atom depends indirectly on all atoms in the system (because they all get updated between each interaction block), but I could be wrong. Let's wait for this update and see.

Thanks for the answer!

**Comment by ktschuett** [comment]
Ah, i was referring to the memory cost of storing the activations for backprop.. Regarding your idea, it should still be possible with multiple interaction layers when you have a cutoff, since you will have a "visual field" of n_interactions*cutoff. So you can split the system across multiple nodes if you accept some duplicated work.

**Comment by OMalenfantThuot** [comment]
I was thinking the same thing at first, sending only the central atom and its neighbors as a forward pass, getting the energy for this atom and looping on the atoms outside the model. I was able to make this work, but the results were off and I'm 99% sure it's because the representation of the neighbors themselves are updated starting from the second interaction block, and these updates depend on atoms not in the initial cutoff.

**Comment by ktschuett** [comment]
Yes, for this to work, the cutoff of the neighborlist needs to be larger than that of the cutoff function inside the model:

`cutoff_nbl = n_interaction*cutoff_internal`

And to avoid too many repeated computation it would make sense to partition the system with some overlap instead of looking at every atom separately.
