### ISSUE TITLE
"strict" argument in md.load_model()

### ISSUE THREAD

**Issue by Sangwon91** [atomistic-machine-learning/schnetpack#31]
https://github.com/atomistic-machine-learning/schnetpack/blob/9caa03c5ca27ab17f02201c4146487c8917521f3/src/schnetpack/md.py#L378

First of all, thank you for the excellent library (nice design patterns, easy-to-use, extendable, and so on...).

I think above line should be
`model.load_state_dict(torch.load(os.path.join(modelpath, 'best_model')), strict=False)`

Otherwise, in my case, `md.load_model()` doesn't work...

**Comment by Sangwon91** [comment]
Thank you for the response.

Actually, it was a simple test.

On `workdir`, I trained `schnet` using the following command
`CUDA_VISIBLE_DEVICES=1,python schnetpack_qm9.py train schnet qm9.db schnet-qm9-100k --split 100000 10000 --cuda`

And I ran simple molecular dynamics simulation using the following code at same directory,
```python
# Load learned model.
model = md.load_model(modelpath="schnet-qm9-100k/") # Error occurs here.

system = "CO2s"

ml_calculator = md.AseInterface(
    molecule_path="simulation/{}.xyz".format(system),
    ml_model=model,
    working_dir="simulation"
)

ml_calculator.init_md(name="{}-md".format(system))
ml_calculator.run_md(steps=1000)

traj_to_xyz("simulation/{}-md.traj".format(system))
```

(CO2s.xyz just an arbitrary xyz file)
Are there any problems?

Thanks!

**Comment by mgastegger** [comment]
I tried your example and it seems to work for me.

Another reason for the issue might be that we made a change in the package after you started training and before running the dynamics.

Did you update schnetpack between training the model and the dynamics? And what does the error message say?

**Comment by Sangwon91** [comment]
I'm not sure about the version issue. But I think I didn't update anything during training and MD run. 
In my system, SchNetPack is installed via pip on conda environment.

The error message is
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-6b9db153d1ba> in <module>()
      1 # Load learned model.
----> 2 model = md.load_model(modelpath="schnet-qm9-100k/")
      3 
      4 system = "CO2s"
      5 

~/anaconda3/envs/schnetpack/lib/python3.5/site-packages/schnetpack/md.py in load_model(modelpath, cuda)
    375 
    376     # Load old parameters
--> 377     model.load_state_dict(torch.load(os.path.join(modelpath, 'best_model')))
    378 
    379     # Set cuda if requested

~/anaconda3/envs/schnetpack/lib/python3.5/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
    767         if len(error_msgs) > 0:
    768             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
--> 769                                self.__class__.__name__, "\n\t".join(error_msgs)))
    770 
    771     def _named_members(self, get_members_fn, prefix='', recurse=True):

RuntimeError: Error(s) in loading state_dict for AtomisticModel:
	Unexpected key(s) in state_dict: "output_modules.atomref.weight". 
```

**Comment by mgastegger** [comment]
Ah, I see where the problem is. For QM9, the free atom energies are subtracted from the total energies, which leads to an additional weight tensor in the state dict. Since we only intended the MD17 trained models (where atomrefs are not subtracted) to be used with the MD script, this tensor is missing in the generated model leading to the error.

I will check, how I can fix this.

**Comment by Sangwon91** [comment]
Can `nn.Module.register_buffer()` resolve the problem?
The registered buffers are included in `nn.Module.state_dict()`.
(batch normalization uses `nn.Module.register_buffer()` for `moving_mean` and `moving_var`.)

**Comment by mgastegger** [comment]
Hi, sorry this took so long.

The general problem was that QM9 was never intended to be used for running molecular dynamics, since no forces are present for training. Hence, as I said above, the atomref tensor was missing from the model built in the `md` module. This would be problematic if one were e.g. to use atom reference energies for the MD17 dataset. I now changed the behavior of `load_model` to load a pickled model file which can be obtained by running the various schnetpack scripts in `export` mode after training a model. This way, `load_model` should be more resilient to changes and special architectural features in the main scripts. The function now also raises an error if loading a model not containing a dedicated energy output layer required for predicting forces, as is the case QM9.
