### ISSUE TITLE
Some columns of QM9 dataset are unclear

### ISSUE THREAD

**Issue by minhtriet** [atomistic-machine-learning/schnetpack#312]
Some columns of QM9 dataset are not straightforward to me (`'_cell', '_cell_offset', '_idx', '_neighbor_mask', '_atom_mask'`). I looked at the data description at [figshare](https://figshare.com/articles/dataset/Readme_file%3A_Data_description_for__Quantum_chemistry_structures_and_properties_of_134_kilo_molecules_/1057641?backTo=/collections/Quantum_chemistry_structures_and_properties_of_134_kilo_molecules/978904), but the link is dead.

Is there a documentation somewhere about this? Thank you

**Comment by mgastegger** [comment]
These columns are used by SchNetPack internally.

`_cell` is the cell used for periodic computations (if requested).
`_cell_offset` are the shift vectors for the periodic images of each atom.
`_neighbor_mask` is a binary mask. Since atoms can have a different number of neighbors, the arrays need to be padded. This mask is an indicator if an entry is a real atom (1) or just padding (0).
All three are generated by an environment provider.

`_idx` is the index of a molecule in the loaded dataset.
