### ISSUE TITLE
Multi-attribute training

### ISSUE THREAD

**Issue by gravity-lhg** [atomistic-machine-learning/schnetpack#332]
Can this Tutorials program load multiple attributes at once for training? If so, where do I need to change the code, in parsing.py? or Only one attribute can be entered for training at a time？

**Comment by Stefaanhess** [comment]
Hey,
training on multiple properties is possible, but not implemented in the `spk_run.py` script.
The easiest way to achieve this is by writing your own script. You can find a basic example script here: [https://github.com/atomistic-machine-learning/schnetpack/blob/master/src/examples/qm9_schnet.py](url). In order to train on multiple properties you can copy+paste the linked script and use a list of output modules instead of a single module (line 20). You will also need to update the loss function in line 25.
