### ISSUE TITLE
Question on using the trained model

### ISSUE THREAD

**Issue by wuziqi-cmu** [atomistic-machine-learning/schnetpack#363]
Hi, I am currently learning the SchNet and had a question: If I have a molecule myself, and it is not from the dataset, why couldn't I just give the trained model an ase.atoms input? Feel like that would make more sense right? If I just want the model to give me predictions on a certain molecule.

**Comment by Stefaanhess** [comment]
Hi @wuziqi-cmu ,
you can also pass your own molecules through the trained model. Although it is not possible to directly pass the `Atoms` object, since the model needs some additional information e.g. neighbors, ..., the computation of the required properties can be done with the `spk.data.AtomsConverter(environment_provider=XXX)`. The converter will transform your `Atoms` to an input directory for the model. Afterwards just wrap your `Atoms` in the converter for your predictions: `model(converter(atoms=atoms))`
You will also need to use the same `EnvironmentProvider` as you have during your training in order to get good results.

**Comment by wuziqi-cmu** [comment]
Got it, that helped a lot! Thanks!
