### ISSUE TITLE
material Project 

### ISSUE THREAD

**Issue by xhjj** [atomistic-machine-learning/schnetpack#394]
Ing to ask  
I use the material Project data (~ 12W) training model to train formation Enengy, and the result (~0.6) is quite different from the result (~0.041) given by the author. What is the reason?

**Comment by ktschuett** [comment]
There have been similar problems in the past. For one, the MP data has been changed since the paper. Since you are experiencing quite a larger error, this seems to be rather a problem with your settings. Are you using the master or dev branch of schnetpack? What do you mean with 12W and which settings do you use?
