### ISSUE TITLE
Towards stress in `dev` branch

### ISSUE THREAD

**Issue by sirmarcel** [atomistic-machine-learning/schnetpack#401]
Hello,

I've started to play around with stress and PaiNN (hah!) in the `dev` branch. As far as I can tell, stress computation doesn't work, and I'd like to try fixing it. I'm making this issue to ask some questions on the internals of the new `schnetpack`, I hope that's ok!

I've had a bit of a poke around and it looks like there's a bunch of smaller problems related to the switch from an explicit batch dimension to the new approach of just concatenating everything and tracking things via `idx_m`. Before I can fix those bugs, I have a question: are the `NeighborListTransform` objects intended to be used in the `model.input_modules`, i.e. to be called during a forward pass, or are they supposed to be "offline" pre-processors that simply provide inputs one structure (molecule) at a time? The code seems to be expecting the latter, which means that the implemented way of computing stress doesn't work, because the computation of the offsets happens outside the computational graph. (In that case, a better way would probably be to differentiate with respect to `Rij` and compute stress as `sum_ij Rij (x) d U d Rij`, which should be straightforward.)

Cheers,

Marcel

**Comment by ktschuett** [comment]
Hi Marcel, 
the neighborlist is used in preprocessing and calculates the indices. Since we compute the actual distance within autograd, it should still work.

@Stefaanhess uses stress in the dev branch and it seems to work. Unfortunately, it is not documented yet:
You have to apply `schnetpack.atomistic.Strain` to the input before passing it into the representation and differentiate w.r.t to `properties.strain`.

@Stefaanhess Maybe you could add an example for this to the new modelzoo with @NiklasGebauer?

**Comment by ktschuett** [comment]
Actually there might be a bug with the cell offsets. I'll have a look...

**Comment by ktschuett** [comment]
Ok, I think the fix is actually a one-liner: We just need to also strain the offsets.

The reason we switched from the variant with the derivatives w.r.t to Rij to the current approach is that you have to resort to quite messy solutions to properly obtain the stress for the Fourier space of the Ewald sum. With the Strain module, you can still take the derivative w.r.t the strain.

**Comment by sirmarcel** [comment]
Alright, the PR with some test fixes is in #402, but this doesn't work across batches. I'm sure you can help me with that, though! :)

**Comment by ktschuett** [comment]
Ok, I have a fix in #403 

1. The indexing into strain_i with idx_i missing, which aligns it with atom pairs as required by the offsets.
2. Your cells apparently don't have the right shape. They should be (1, 3, 3) before batching.

**Comment by sirmarcel** [comment]
Thanks for fixing. After changing the shape of `cell` in my tests, the results look reasonable!

**Comment by sirmarcel** [comment]
Oh, also, just in case the `cell` ends up getting used anywhere: I'm pretty sure the correct way to apply strain to the `cell` would be:
```
inputs[properties.cell] = inputs[properties.cell] + torch.matmul(
            inputs[properties.cell], strain.transpose(1, 2)
        )
```
This is because the `cell` has the basis vectors along the first dimension.

I've updated the [gist](https://gist.github.com/sirmarcel/7b7f4ddb617c10db4a26dd7e75f1aea5) with an example where I explicitly compute the `offsets` during the forward pass; this produces the following with the current `dev` branch:
```
strain_compute_offsets
[[[  -2.6313148  -91.92748   -387.888    ]
  [  85.96726     -5.8808103 -314.20786  ]
  [ 371.3547     288.0463     -33.894863 ]]]

ase
[[ -2.63129346  -2.98017313  -8.2668025 ]
 [ -2.98017313  -5.88085113 -13.08076411]
 [ -8.2668025  -13.08076411 -33.89520126]]
```

Changing to the form above fixes this.

**Comment by sirmarcel** [comment]
Yup, this works. It may be slightly more readable to just change the line with the `cell` as above, but both seem to be equivalent and give identical results in my improvised test.
