### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by braxtonowens** [atomistic-machine-learning/schnetpack#487]
Would either SchNet or PaiNN work on very large systems >35,000 atoms? Assuming it would, do you think it could distinguish large pure systems? Basically only using positional information?

**Comment by Stefaanhess** [comment]
Hey @braxtonowens ,
I assume, that you should be able to train SchNet and PaiNN on very large datasets. In general the models learn the forces better for larger systems, because you have many more local environments to train on.
You would need to try it out how good the model can learn on your dataset. I am afraid though, that you will need a very large GPU in order to train a model on such big systems...
