### ISSUE TITLE
ACSFs

### ISSUE THREAD

**Issue by jokpreiksa** [atomistic-machine-learning/schnetpack#490]
Why version 2.0 does not seem to have ACSFs implemented? Is there any particular reason for it?

**Comment by mgastegger** [comment]
There are a few different reasons for this.

Compared to the message passing frameworks, ACSFs would have needed several special adaptations of the whole code base. E.g. in order for the ACSFs to give acceptable results they need to be normalized before training, separate networks need to be used for every element, angular ACSFs need to collect triples of atoms, etc. This would have required a surprising amount of ad-hoc fixes, cluttering the code and making things needlessly complicated. 
 
We also found, that even basic MPNNs seem to consistently outperform ACSFs and wACSFs (see e.g. the [first SchNetPack paper](https://arxiv.org/abs/1809.01072)). This effect is more pronounced for equivariant MPNNs such as PaiNN. Another disadvantage is the use of one-hot encoding for different elements, which causes the number of angular SFs for an atom to grow quadratically with the number of atom types. This leads to very large feature vectors when more than 4-5 elements are present.

Since we didn't see enough of a benefit to justify the added complexity in the code, we decided to exclude ACSFs at some point during development.
