### ISSUE TITLE
Training on atomic properties

### ISSUE THREAD

**Issue by brancip** [atomistic-machine-learning/schnetpack#494]
Hello
Is it a plan to create a specific tutorial for training a NN on atomic properties?
I was trying to replicate the tutorial https://schnetpack.readthedocs.io/en/stable/tutorials/tutorial_02_qm9.html

but I couldn't do it, I tried to use my own data and the get_atomref method for both my data and the qm9 examples, but it gives me `{'property': None} `

Could you clarify the use of the atomref method and its role in atomic properties training?

Regards

**Comment by Stefaanhess** [comment]
Hi @brancip ,

currently we have not planned to add an additional tutorial on training a NN on atomic properties.
In tutorial 1 you can find information about preparing you own datasets. In order to train on that dataset, you could copy-paste the QM9 config file and replace the property name.
The atomref data can be used to provide an estimate of the molecular energy, that is based on simple statistics. This can help to improve the training performance, because the model only needs to learn the difference between the estimate and the true properties. Some datasets do provide these atomref values, but for most properties/datasets these statistics are not provided. In that case you can just set `add_atomrefs=False`. Otherwise you would need to compute these statistics by yourself and add them to the metadata in your database.
Did you download the QM9 dataset with our `QM9`-class? In that case, the atomrefs should be present. You can check this with:

```
from ase.db import connect
with connect("path-to-qm9.db") as db:
    print(db.metadata)
```
