### ISSUE TITLE
Predicting analytical Hessian after training a model on energy and forces

### ISSUE THREAD

**Issue by zyt0y** [atomistic-machine-learning/schnetpack#507]
Dear all,

If I haved trained a PaiNN model on energy and forcies (`spk.atomistic.Atomwise` and `spk.atomistic.Forces`), is it possible to output analytical Hessian when using the trained model? I notice that there is a function called `activate_model_stress()` in `spk.md.utils` which is similar to what I want for analytical Hessian.

Best,
Zeyuan

**Comment by mgastegger** [comment]
Hi Zeyuan,

this might be a little bit tricky. The `spk.atomistic.Forces` module used in the default Potential has no internal instructions for computing the Hessian (it has for the stress).

There is the more general `spk.atomistic.Response` module which can compute analytical Hessians.
So one approach would be to load your trained model and swap the `spk.atomistic.Forces` in the `output_modules` list for an instance of `spk.atomistic.Response` where Hessian are requested. Something like:
```
import torch
import schnetpack as spk
import schnetpack.properties as spk_properties

model = torch.load("PATH/TO/MODEL")

response = spk.atomistic.Response(
    energy_key = spk_properties.energy, # name for potential energy in model output
    response_properties = [
        spk_properties.hessian, 
        spk_properties.forces, # if desired
        spk_properties.stress, # if desired
   ]
)

# replace Forces module in output modules (here at index 1)
model.output_modules[1] = response

# save modified model
torch.save(model, "HESSIAN/MODEL")
```

The resulting model should now return the Hessians during prediction.
The Hessians tensors will be flattened and stacked for the different molecules, with the dimension `[ n_atoms_1 * n_atoms_1 n_atoms_2 * n_atoms_2 ... n_atoms_N * n_atoms_N ]` where 1 to N would be the molecules.

Please note that this will be relatively expensive, especially if many atoms are present in your system due to the way derivatives are computed in pytorch.

**Comment by zyt0y** [comment]
Hi @mgastegger 

I tried your script for converting my trained model and wrote another script to use the converted model
```python
import torch
import schnetpack.transform as trn
from schnetpack.interfaces.ase_interface import AtomsConverter
from ase.io import read

atoms = read('PATH/TO/ATOMS')

model = torch.load('HESSIAN/MODEL', map_location='cpu')
model = model.eval()

converter = AtomsConverter(trn.ASENeighborList(cutoff=5.0))

model_inputs = converter(atoms)
model_results = model(model_inputs)


print(model.output_modules)
print('\n')
print(model.output_modules[1].map_properties)
print(model.output_modules[1].response_properties)
print(model.output_modules[1].required_derivatives)
print(model.output_modules[1].derivative_instructions)
print('\n')
print(list(model_results.keys()))
```

The output looks like this
```
ModuleList(
  (0): Atomwise(
    (outnet): Sequential(
      (0): Dense(in_features=128, out_features=64, bias=True)
      (1): Dense(
        in_features=64, out_features=1, bias=True
        (activation): Identity()
      )
    )
  )
  (1): Response()
  (2): DipoleMoment(
    (outnet): Sequential(
      (0): Dense(in_features=128, out_features=64, bias=True)
      (1): Dense(
        in_features=64, out_features=1, bias=True
        (activation): Identity()
      )
    )
  )
)


{'hessian': 'hessian', 'forces': 'forces'}
['hessian', 'forces']
['_positions']
{'dEdR': True, 'd2EdR2': True, 'dEdF': False, 'd2EdFdR': False, 'd2EdF2': False, 'd3EdF2dR': False, 'dEdB': False, 'dEdI': False, 'd2EdBdI': False, 'd2EdI2': False, 'dEds': False}


['energy', 'dipole_moment', 'forces', 'partial_charges']
```
It seems that hessian has been calculated, but not saved in `model_results`. My problem is quite similar with @rschireman
.  Any suggestions?

**Comment by mgastegger** [comment]
One thing I forgot is that the model outputs list also needs to be updated.
It is used to filter the results.
So one would also have to update those before saving the modified model:
```
model.model_outputs.append(spk_properties.hessian)
```
(Assuming everything else is already present.)

Could be that everything is computed an the model just filters out the Hessians.

**Comment by zyt0y** [comment]
`model.model_outputs.append(spk_properties.hessian)` solves my problem. Thank you very much @mgastegger

**Comment by rschireman** [comment]
works with my model as well!
