### ISSUE TITLE
[Usage Question] Predicted and Actual Energies are Same / How to call energies from AtomsDataModule

### ISSUE THREAD

**Issue by owen-rett** [atomistic-machine-learning/schnetpack#510]
Hello, 
I'm in the process of learning how to use Schnetpack, and I've managed to get a model trained (or at least I believe so), and am trying to calculate force/energy errors from the trained model. Hence I've written a function that takes an AtomsDataModule, extracts the test dataset from it, and then gets predictions from the model on the test dataset. 

I'm getting the "actual" energies by calling atom_mod.test_dataset, and then using AtomsConverter on one structure in that dataset. I think this is probably where I'm messing up, however taking the energy from the raw Atom_Data_module file seems incredibly far off, unless the energy there is a per-atom value. 

However, after calculating the r^2 and rmse of the energies, I've noticed that the r^2 and rmse are 1.0 and 0.0 respectively, which indicates that I'm doing something wrong, or that I've somehow gotten a perfect model despite using only 5 epochs to train. I've attached the code I'm using. 

[Parity_Plot.txt](https://github.com/atomistic-machine-learning/schnetpack/files/10993827/Parity_Plot.txt)

**Comment by Stefaanhess** [comment]
Hi @owen-rett ,

I just had a look at you code snippet. The reason, why your code results in perfect accuracy is due to the way `schnetpack` processes the data during the prediction. We use the `inputs` dictionary to store all relevant input properties for the model, but also to update it with all relevant properties, that are computed by the model. This is also the case for the predictions of the model. In your script, the labels are stored in the `inputs` dictionary, but the model will just overwrite them with the predictions. So in the end you compare the model predictions to itself, but the labels are overwritten.
So you would need to extract the targets, before calling `model(inputs)`.
Maybe this is not the optimal solution by `schnetpack` and I will keep this in mind for future changes.

Let me know if that helps!

**Comment by Stefaanhess** [comment]
You can leave it open for further questions. Once you have a solution, feel free to close the issue!

**Comment by owen-rett** [comment]
Hello, 
I don't think I'll have enough time to look into fixing this issue for at least 3-4 weeks, so I think I'll close this issue and open a new one when I am able to focus on getting parity plots made for my installation of SchNetPack.
