### ISSUE TITLE
Training a NN Across Multiple Nodes

### ISSUE THREAD

**Issue by JordD04** [atomistic-machine-learning/schnetpack#514]
My cluster has 3 GPUs per node which is not always enough VRAM.
I increased the number of nodes from 1 to 2 in slurm, giving me 6 GPUs total, but the "CUDA out of memory" is unchanged (`39.41 GiB total capacity` regardless of the number of nodes).
How can I get SchNetPack to access VRAM across multiple nodes?
I've tried adding `'trainer.num_nodes=2', 'trainer.devices=6'` to spktrain but that returns: 
`MisconfigurationException('You requested gpu: [0, 1, 2, 3, 4, 5]\n But your machine only has: [0, 1, 2]')`
Which makes me feel like SchNetPack can't find the 2nd set of GPUs.

How do I fix this?

**Comment by jnsLs** [comment]
By default SchNetPack uses the pytorch-lightning Trainer. So I would expect that this is not an issue of the SchNetPack code. Have you already tried training, e.g., a simple linear model using only pytroch-lightning on two nodes?

**Comment by jnsLs** [comment]
Are there any news? Did you manage to train a simple pytorch-lightning model on multiple nodes?

**Comment by JordD04** [comment]
I've experimented with the "Lightning in 15 minutes" tutorial here: https://lightning.ai/docs/pytorch/stable/starter/introduction.html

That seems to be yielding a similar issue, so perhaps it's a problem with my machine. 

Steps 1-5 work fine but as soon as I add:

trainer = pl.Trainer(
    devices=4,
    accelerator="gpu",
 )

I get: 
lightning.fabric.utilities.exceptions.MisconfigurationException: You requested gpu: [0, 1, 2, 3]
 But your machine only has: [0, 1, 2]

**Comment by jnsLs** [comment]
Yes, that indicates that the problem is between pytorch-lightning and your machine. 
The modular design of SchNetPack also allows for training models without using pytorch-lightning. 
This tutorial describes the general training procedure for SchNetPack models:
https://schnetpack.readthedocs.io/en/latest/tutorials/tutorial_02_qm9.html

You could, e.g., implement a custom trainer similar to the one in SchNetPack 1.0.0.

**Comment by JordD04** [comment]
I got some help from the admins on my cluster and the main issue was that I thought `devices` was total number of devices, not the number of devices *per* node.
That got my test case working, but for SchNetPack the training never starts and it just prints the following to the slurm.out multiple times:
`[torch.distributed.distributed_c10d][INFO] - Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=48, worker_count=1, timeout=0:30:00)`

**Comment by Stefaanhess** [comment]
Hey @JordD04 ,

unfortunately it is not possible to derive many conclusions from your output file. I also think this is either a general issue with pytorch/lightning or with you HPC system. If it was related to schnetpack, I would expect to logfile to at least contain the printed header and the settings, because that is printed before any of the schnetpack code is even running ([see cli.py](https://github.com/atomistic-machine-learning/schnetpack/blob/master/src/schnetpack/cli.py) ).
In order to find out what is going on, I think you would need to start a new script from scratch and see at what point your run fails. First start without any schnetpack code, but only with pytorch-lightning. Create a dummy model, dummy data and try if you can fit it with the lightning trainer. If everything works fine and the dummy model trains well, you can have a look at our [cli.py](https://github.com/atomistic-machine-learning/schnetpack/blob/master/src/schnetpack/cli.py) and build your own script and sequentially add new stuff to it. Then see at what point you get any errors.

I am afraid, that this is the only advise we can give at this point.

If you HPC does not allow to train on multiple nodes in parallel or this is generally not possible, you could also avoid doing this by reducing the batchsize and `n_atom_basis`/`n_interactions`.

Best,
Stefaan

**Comment by JordD04** [comment]
Hey Stefaan,
Thanks for your help. I appreciate the problem is difficult to diagnose. I'm considering a few a few approaches to try and address the issue (including moving to a machine with more GPUs per node). 

The HPC machine definitely allows training across multiple nodes. I think it's probably an issue with the modules I have loaded. 
Unfortunately, simplifying the NN isn't an option. I can train a NN that yields seemingly good force and stress errors, but when I try to do a geometry optimisation, the cell crushes. Interestingly, if I train only on forces, the geometry optimisations work really well. I figure I need to expand my architecture to get better performance but i'm being capped by my RAM limitations.
