### ISSUE TITLE
Issue training PaiNN

### ISSUE THREAD

**Issue by ireaml** [atomistic-machine-learning/schnetpack#521]
Hi,

Was trying to train a PaiNN model to predict an intensive property for some materials, following the [tutorial in the docs](https://schnetpack.readthedocs.io/en/latest/tutorials/tutorial_02_qm9.html), but I get the following error:
```
RuntimeError: mat1 and mat2 must have the same type
```
As far as I understand, it's related to a problem with the type of the input matrices, but I've generated the dataset following the [Preparing and loading your data tutorial](https://schnetpack.readthedocs.io/en/latest/tutorials/tutorial_01_preparing_data.html), so not sure why there would be an issue.

I attach the notebook I used to generate the SchNet dataset and train the model, as well as the dataset.

Thanks a lot!

[data.zip](https://github.com/atomistic-machine-learning/schnetpack/files/11242123/data.zip)

**Comment by jnsLs** [comment]
Hello, 
your data consists of float64 arrays but your model works with float32. 
Therefore, you need to include a transform in your datamodule that casts your inputs to float32.

Instead of 

`# Alternatively, can use DataModule
from schnetpack.data import AtomsDataModule

datamodule = AtomsDataModule(
    datapath='./new_dataset3.db',
    batch_size=2,
    num_train=8,
    num_val=1,
    num_test=1,
    transforms=[trn.ASENeighborList(cutoff=5.)]
)`

you should write
`# Alternatively, can use DataModule
from schnetpack.data import AtomsDataModule

datamodule = AtomsDataModule(
    datapath='./new_dataset3.db',
    batch_size=2,
    num_train=8,
    num_val=1,
    num_test=1,
    transforms=[
        trn.ASENeighborList(cutoff=5.),         
        trn.CastTo32(),
    ]
)`

Also a remark: you seem to use different cutoffs for your model and your data. I would recommend using the same cutoff to have a consistent neighbor list.

**Comment by ireaml** [comment]
Thanks a lot!
