### ISSUE TITLE
Extracting the atomic embeddings for a molecule after a model is trained

### ISSUE THREAD

**Issue by jindal92** [atomistic-machine-learning/schnetpack#569]
Hi everyone, 
I want to visualise and use the atomic representation for a molecule after the schnet training is done. In the best_model file, I found a 100*input_feature vector for the embeddings, but how to use it to estimate the representation for a specific atom in a molecule?

**Comment by Stefaanhess** [comment]
Hi,
the embedding is learned for every atom type (not every atom). So in order to get the embedding for a specific atom, first get the atom type and find the embedding layer with the atomic number as an index. The dimensions of the embedding are 100*n_features, because the expected maximum atomic number is 100.

**Comment by jindal92** [comment]
Hi, 

Thanks a lot! So, If I have a dataset with molecule having 2 C atoms and 2 H atoms, then I should get two vectors for embeddings, one corresponding to C (index:6) and other corresponding to H (index:1)?

**Comment by Stefaanhess** [comment]
Yes :)

**Comment by jindal92** [comment]
Okay, so after I get the embedding vector for a specific atom type, How to obtain the representation  for a specific atom in a molecule? Like some kind of postprocessing?

**Comment by jindal92** [comment]
Thank you so much. I will try this and get back to you if I am still having any problems :)

**Comment by jindal92** [comment]
It worked, Thanks a lot!
