### ISSUE TITLE
Doubt about schnetpack.environment

### ISSUE THREAD

**Issue by dondavidsb** [atomistic-machine-learning/schnetpack#590]
Hi,
I a trying to import some modules from the schnetpack while doing a tutorial (from some years ago). 
The code is trying to import SimpleEnvironmentProvider from schnetpack.environment, but I am not able to find it. Maybe it has been changed to other module or name?

I paste the error:
  File "/home/poasibrd/berlin/torchmd-net-legacy/scripts/light_train.py", line 15, in <module>
    from schnetpack.environment import SimpleEnvironmentProvider
ModuleNotFoundError: No module named 'schnetpack.environment'

Thank you.
David

**Comment by jnsLs** [comment]
Hi David, 

we have published a new version of schnetpack (schnetpack 2.0.0). Your error looks like you are using the new version. The SimpleEnvironmentProvider however was only available in the old version. 

Are you using a tutorial we provided?

I would recommend using the new version of schnetpack with our tutorials, since for the old version (schnetpack 1.0.0) the maintenance is discontinued. However, if you still prefer using the old version you can do so by switching to the branch https://github.com/atomistic-machine-learning/schnetpack/tree/schnetpack1.0

Best regards, Jonas
