### ISSUE TITLE
GDML from the sgdml package

### ISSUE THREAD

**Issue by jhrmnn** [atomistic-machine-learning/schnetpack#65]
I talked to @stefanch, and maybe it makes more sense to have the GDML code in the `sgdml` package, and just import it in `schnetpack` and have `sgdml` as a dependency. What do you think about that? If you agree, should I make `sgdml` a hard or an optional "extras" dependency of `schnetpack`?

**Comment by ktschuett** [comment]
Not a hard dependency, since most people won't use GDML. But what part of
the code of schnetpack would actually be used? You basically wrote a
vanilla pytorch module at this point. So I don't think we need a
requirement at all.

Jan Hermann <notifications@github.com> schrieb am Do., 7. März 2019 um
17:04 Uhr:

**Comment by jhrmnn** [comment]
Ah, correct, I haven't realized that. Ok, so I'll just move the code to the sgdml package, and revert all the changes to schnetpack. Sorry for the hassle.
