### ISSUE TITLE
Storing the symmetry functions calculated

### ISSUE THREAD

**Issue by lmj1029123** [atomistic-machine-learning/schnetpack#90]
Hi,

I am wondering whether there is an easy way to store the symmetry functions calculated for the data, so it doesn't need to calculate them for every epoch. It is a very time consuming step for my model. Thanks!

Best,
Mingjie

**Comment by mgastegger** [comment]
Sorry for the long wait. The functionality is not implemented yet.

However, what one could do is to iterate over the data once using the initialized BehlerSFBlock and store the computed symmetry functions directly in the db.

I will have a look at it.

**Comment by mgastegger** [comment]
After comparing the GPU training times with stored symmetry functions and the on the fly computation currently implemented, I found the following:

Unfortunately, storing the SFs does not lead to a better performance. Due to the I/O overhead, the algorithm computing them on the fly is significantly faster, even for small molecules. Moreover, even when ignoring the above issue, storing the SFs is only feasible if no derivatives (forces) should be computed. In the case of forces, one needs to evaluate
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbf{F}_\alpha&space;=&space;-\sum_i^{N_\mathrm{Atoms}}&space;\sum_\sigma^{N_\mathrm{SF}}&space;\frac{\partial&space;E_i}{\partial&space;G^i_\sigma}&space;\frac{\partial&space;G^i_\sigma}{\mathbf{R}_\alpha}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbf{F}_\alpha&space;=&space;-\sum_i^{N_\mathrm{Atoms}}&space;\sum_\sigma^{N_\mathrm{SF}}&space;\frac{\partial&space;E_i}{\partial&space;G^i_\sigma}&space;\frac{\partial&space;G^i_\sigma}{\mathbf{R}_\alpha}" title="\mathbf{F}_\alpha = -\sum_i^{N_\mathrm{Atoms}} \sum_\sigma^{N_\mathrm{SF}} \frac{\partial E_i}{\partial G^i_\sigma} \frac{\partial G^i_\sigma}{\mathbf{R}_\alpha}" /></a>
for every atom, where G is the SF vector on each atom. If the SFs are stored, one would also need to store the <a href="https://www.codecogs.com/eqnedit.php?latex={\partial&space;G^i_\sigma}&space;/&space;{\mathbf{R}_\alpha}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?{\partial&space;G^i_\sigma}&space;/&space;{\mathbf{R}_\alpha}" title="{\partial G^i_\sigma} / {\mathbf{R}_\alpha}" /></a>, which amounts to <a href="https://www.codecogs.com/eqnedit.php?latex=3&space;\times&space;{N_\mathrm{Atoms}}^2&space;\times&space;{N_\mathrm{SF}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?3&space;\times&space;{N_\mathrm{Atoms}}^2&space;\times&space;{N_\mathrm{SF}}" title="3 \times {N_\mathrm{Atoms}}^2 \times {N_\mathrm{SF}}" /></a> elements per molecule. This will definitively lead to massive I/O problems. As such, storing symmetry functions is not really practical.

If the calculation is slow due to the number of atoms in the system, it might help to choose a suitable cutoff and exchange the basic environment provider `schnetpack.environment.SimpleEnvironmentProvider` to `schnetpack.environment.AseEnvironmentProvider`, as this reduces the number of neighbors considered in the SFs to the relevant cutoff regions.

**Comment by lmj1029123** [comment]
I see. Thanks a lot for the detailed reply.
